.\"     Title: define hostescalation
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE HOSTESCALATIO" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_hostescalation
.SH "BESCHREIBUNG"
.PP
Host\-Eskalationen sind
\fIkomplett optional\fR
und werden benutzt, um Benachrichtigungen für einen bestimmten Host zu eskalieren\&. Mehr Informationen, wie Eskalationen arbeiten, finden Sie hier\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&.

   define hostescalation{    
      \fIhost_name\fR                         host_name
      hostgroup_name                    hostgroup_name
      \fIcontacts\fR                          contacts
      \fIcontact_groups\fR                    contactgroup_name
      \fIfirst_notification\fR                #
      \fIlast_notification\fR                 #
      \fInotification_interval\fR             #
      escalation_period                 timeperiod_name
      escalation_options                [d,u,r]
      escalation_condition              <condition> ( [ & / | ] <condition> )*
      first_down_notification           #
      last_down_notification            #
      first_unreachable_notification      #
      last_unreachable_notification      #
   }    
    