.\"     Title: define hostdependency
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE HOSTDEPENDENC" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_hostdependency
.SH "BESCHREIBUNG"
.PP
Host\-Abhängigkeiten sind ein fortgeschrittenes Feature von Icinga, das es Ihnen erlaubt, Benachrichtungen von Hosts in Abhängigkeit vom Status eines oder mehrerer Hosts zu unterdrücken\&. Host\-Abhängigkeiten sind optional und zielen hauptsächlich auf fortgeschrittene Benutzer mit komplizierten Überwachungsumgebungen\&. Mehr Informationen, wie Host\-Abhängigkeiten arbeiten (lesen Sie dies!), finden Sie hier\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&.

   define hostdependency{    
      \fIdependent_host_name\fR               host_name
      dependent_hostgroup_name          hostgroup_name
      \fIhost_name\fR                         host_name
      hostgroup_name                    hostgroup_name
      inherits_parent                   [0/1]
      execution_failure_criteria        [o,d,u,p,n]
      notification_failure_criteria      [o,d,u,p,n]
      dependency_period                 timeperiod_name
   }    
    