.\"     Title: define servicedependency
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE SERVICEDEPEND" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_servicedependency
.SH "BESCHREIBUNG"
.PP
Service\-Abhängigkeiten sind ein fortgeschrittenes Feature von Icinga, das es Ihnen erlaubt, Benachrichtungen und aktive Prüfungen von Services in Abhängigkeit vom Status eines oder mehrerer Services zu unterdrücken\&. Service\-Abhängigkeiten sind optional und zielen hauptsächlich auf fortgeschrittene Benutzer mit komplizierten Überwachungsumgebungen\&. Mehr Informationen, wie Service\-Abhängigkeiten arbeiten (lesen Sie dies!), finden Sie hier\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&. Trotz allem müssen Sie mindestens ein Kriterium angeben, damit die Definition von Nutzen ist\&.

   define servicedependency{    
      \fIdependent_host_name\fR               host_name
      dependent_hostgroup_name          hostgroup_name
      \fIdependent_service_description\fR      service_description
      \fIhost_name\fR                         host_name
      hostgroup_name                    hostgroup_name
      \fIservice_description\fR               service_description
      inherits_parent                   [0/1]
      execution_failure_criteria        [o,w,u,c,p,n]
      notification_failure_criteria      [o,w,u,c,p,n]
      dependency_period                 timeperiod_name
   }    
    