.\"     Title: define hostgroup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE HOSTGROUP" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_hostgroup
.SH "BESCHREIBUNG"
.PP
Eine Hostgruppen\-Definition wird benutzt, um einen oder mehrere Hosts zu gruppieren, um die Konfiguration mit Objekt\-Tricks zu vereinfachen oder für Anzeigezwecke in den CGIs\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&.

   define hostgroup{    
      \fIhostgroup_name\fR                    hostgroup_name
      \fIalias\fR                             alias
      members                           hosts
      hostgroup_members                 hostgroups
      notes                             note_string
      notes_url                         url
      action_url                        url
   }    
    