.\"     Title: define module
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE MODULE" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_module
.SH "BESCHREIBUNG"
.PP
Eine Module\-Definition wird benutzt, um Informationen zu einem Modul anzugeben\&. Sie kann anstatt eines broker_module\-Eintrags in der Hauptkonfigurationsdatei verwendet werden und ist deshalb flexibler (Sie können cfg_file/cfg_dir\-Einträge benutzen, um sie einzuschließen)\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
Moduldefinitionen sind seit Icinga 1\&.4 verfügbar\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&.

   define module{    
      \fImodule_name\fR                       module name
      \fIpath\fR                              path
      args                              arguments
      module_type                       neb
   }    
    