.\"     Title: define serviceescalation
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE SERVICEESCALA" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_serviceescalation
.SH "BESCHREIBUNG"
.PP
Serviceeskalationen sind
\fIkomplett optional\fR
und werden benutzt, um Benachrichtigungen für einen bestimmten Service zu eskalieren\&. Mehr Informationen, wie Eskalationen arbeiten, finden Sie hier\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&.

   define serviceescalation{    
      \fIhost_name\fR                         host_name
      hostgroup_name                    hostgroup_name
      servicegroup_name                 servicegroup_name
      \fIservice_description\fR               service_description
      \fIcontacts\fR                          contacts
      \fIcontact_groups\fR                    contactgroup_name
      \fIfirst_notification\fR                #
      \fIlast_notification\fR                 #
      \fInotification_interval\fR             #
      escalation_period                 timeperiod_name
      escalation_options                [w,u,c,r]
      escalation_condition              <condition> ( [ & / | ] <condition> )*
      first_warning_notification        #
      last_warning_notification         #
      first_critical_notification       #
      last_critical_notification        #
      first_unknown_notification        #
      last_unknown_notification         #
   }    
    