.\"     Title: define hostextinfo
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE HOSTEXTINFO" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_hostextinfo
.SH "BESCHREIBUNG"
.PP
Einträge für erweiterte Hostinformationen sind grundsätzlich dazu gedacht, die Ausgaben der status\-, statusmap\-
und extinfo\-CGIs schöner aussehen zu lassen\&. Sie haben keinen Einfluss auf die Überwachung und sind vollständig optional\&.
.PP
[IMAGE]\&[1]
Hinweis: Alle Direktiven der erweiterten Hostinformations\-Definition sind auch in den Host\-Definitionen verfügbar\&. Dadurch können Sie entscheiden, die nachstehenden Direktiven in Ihren Host\-Definitionen zu benutzen, wenn es Ihre Konfigurationen vereinfacht\&. Separate erweiterte Hostinformations\-Definitionen werden weiterhin unterstützt, um Rückwärtskompatibilität zu gewährleisten\&.
.PP
Anmerkung:
\fI"Direktiven"\fR
werden benötigt, die anderen sind optional\&. Trotz allem müssen Sie mindestens ein Kriterium angeben, damit die Definition von Nutzen ist\&.

   define hostextinfo{    
      \fIhost_name\fR                         host_name
      notes                             note_string
      notes_url                         url
      action_url                        url
      icon_image                        image_file
      icon_image_alt                    alt_string
      vrml_image                        image_file
      statusmap_image                   image_file
      2d_coords                         x_coord,y_coord
      3d_coords                         x_coord,y_coord,z_coord
   }    
    .SH "NOTES"
.IP " 1." 4
../images/tip.gif
