.\"     Title: define servicedependency
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE SERVICEDEPEND" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_servicedependency
.SH "DESCRIPTION"
.PP
Service dependencies are an advanced feature of Icinga that allow you to suppress notifications and active checks of services based on the status of one or more other services\&. Service dependencies are optional and are mainly targeted at advanced users who have complicated monitoring setups\&. More information on how service dependencies work (read this!) can be found here\&.
.PP
\fIDefinition Format:\fR
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
\fI"Directives"\fR
are required while the others are optional\&. However, you must supply at least one type ofcriteria for the definition to be of much use\&.


   define servicedependency{    
      \fIdependent_host_name\fR               host_name
      dependent_hostgroup_name          hostgroup_name
      \fIdependent_service_description\fR      service_description
      \fIhost_name\fR                         host_name
      hostgroup_name                    hostgroup_name
      \fIservice_description\fR               service_description
      inherits_parent                   [0/1]
      execution_failure_criteria        [o,w,u,c,p,n]
      notification_failure_criteria      [o,w,u,c,p,n]
      dependency_period                 timeperiod_name
   }    
    