.\"     Title: define timeperiod
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE TIMEPERIOD" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_timeperiod
.SH "DESCRIPTION"
.PP
A time period is a list of times during various days that are considered to be "valid" times for notifications and service checks\&. It consists of time ranges for each day of the week that "rotate" once the week has come to an end\&. Different types of exceptions to the normal weekly time are supported, including: specific weekdays, days of generic months, days of specific months, and calendar dates\&.
.PP
\fIDefinition Format:\fR
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
\fI"Directives"\fR
are required while the others are optional\&.


   define timeperiod{    
      \fItimeperiod_name\fR                   timeperiod_name
      \fIalias\fR                             alias
      [weekday]                         timeranges
      [exception]                       timeranges
      exclude                           [timeperiod1,timeperiod2,\&.\&.\&.,timeperiodn]
   }    
    