.\"     Title: define contactgroup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE CONTACTGROUP" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_contactgroup
.SH "DESCRIPTION"
.PP
A contact group definition is used to group one or more contacts together for the purpose of sending out alert/recovery notifications\&.
.PP
\fIDefinition Format:\fR
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
\fI"Directives"\fR
are required while the others are optional\&.


   define contactgroup{    
      \fIcontactgroup_name\fR                 contactgroup_name
      \fIalias\fR                             alias
      members                           contacts
      contactgroup_members              contactgroups
   }    
    