.\"     Title: define command
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE COMMAND" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_command
.SH "DESCRIPTION"
.PP
A command definition is just that\&. It defines a command\&. Commands that can be defined include service checks, service notifications, service event handlers, host checks, host notifications, and host event handlers\&. Command definitions can contain macros, but you must make sure that you include only those macros that are "valid" for the circumstances when the command will be used\&. More information on what macros are available and when they are "valid" can be found here\&. The different arguments to a command definition are outlined below\&.
.PP
\fIDefinition Format:\fR
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
\fI"Directives"\fR
are required while the others are optional\&.


   define command{    
      \fIcommand_name\fR                      command_name
      \fIcommand_line\fR                      command_line
   }    
    