.\"     Title: define contact
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2011.08.24
.\"    Manual: 
      
.\"    Source: Icinga 1.5
.\"
.TH "DEFINE CONTACT" "8" "2011.08.24" "Icinga 1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
define_contact
.SH "DESCRIPTION"
.PP
A contact definition is used to identify someone who should be contacted in the event of a problem on your network\&. The different arguments to a contact definition are described below\&.
.PP
\fIDefinition Format:\fR
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
\fI"Directives"\fR
are required while the others are optional\&.


   define contact{    
      \fIcontact_name\fR                      contact_name
      alias                             alias
      contactgroups                     contactgroup_names
      \fIhost_notifications_enabled\fR        [0/1]
      \fIservice_notifications_enabled\fR      [0/1]
      \fIhost_notification_period\fR          timeperiod_name
      \fIservice_notification_period\fR       timeperiod_name
      \fIhost_notification_options\fR         [d,u,r,f,s,n]
      \fIservice_notification_options\fR      [w,u,c,r,f,s,n]
      \fIhost_notification_commands\fR        command_name
      \fIservice_notification_commands\fR      command_name
      email                             email_address
      pager                             pager_number or pager_email_gateway
      address\fIx\fR                          additional_contact_address
      can_submit_commands               [0/1]
      retain_status_information         [0/1]
      retain_nonstatus_information      [0/1]
   }    
    